runtime: python39

handlers:
  # Serve the main HTML file
  - url: /
    static_files: index.html
    upload: index.html

  # Serve all static files
  - url: /(.*)
    static_files: \1
    upload: (.*)

# Optional: Configure automatic scaling
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
